# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeTestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTestApp
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'ReactNativeTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeTestApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeTestApp-tvOS

  target 'ReactNativeTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
